[global]
daemonize = no
error_log = /run/webdip/logs/php-fpm.log
pid = /run/webdip/php-fpm.pid

[webdip]
user = root
group = root
listen = 127.0.0.1:9000
listen.allowed_clients = 127.0.0.1
pm = static
pm.max_children = 4
catch_workers_output = yes
clear_env = yes
chdir = /application
php_admin_flag[log_errors] = on
php_admin_flag[display_errors] = off
php_admin_value[error_log] = /run/webdip/logs/php.log

php_admin_value[sendmail_path] = /bin/true
